source "https://rubygems.org"

ruby '3.1.2'

# Rails
gem "rails", "~> 7.2.2", ">= 7.2.2.2"

# Base de datos
gem "pg", "~> 1.1"

# Servidor web
gem "puma", ">= 5.0"

# CORS
gem "rack-cors"
# Performance booster (cache de archivos)
gem 'bootsnap', '>= 1.18.6', require: false


# Gems opcionales para desarrollo/test
group :development, :test do
  gem "debug", platforms: %i[mri mswin mswin64 mingw x64_mingw], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

# Gems opcionales para producción
group :production do
  # gems específicas para producción si necesitás
end

